# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET CI/CD Pipeline for the main branch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: Main

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      env: 
        version: 1
      run: dotnet restore
    - name: Build
      env: 
        version: 1
      run: dotnet build --no-restore
    - name: Test
      env: 
        version: 1
      run: dotnet test --no-build --verbosity normal

  deploy:
    if: github.ref == 'refs/heads/main' # this prevents that the "deploy" job is executed during Pull Request checks
    runs-on: Main
    needs: build

    strategy:
      matrix:
        dotnet: ["8.0.x"]
    
    steps:
    - name: Publish
      env: 
        version: 1
      run: dotnet publish -c Release -o /home/LSPDFRHelper

    - name: Store build info in file
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        echo "Current Branch: $BRANCH_NAME | Commit Hash: $GITHUB_SHA" > /home/LSPDFRHelper/build_info.txt
      continue-on-error: true

    - name: Restart app
      run: pm2 restart 0
