name: .NET CI/CD Pipeline for the main branch

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: Main
        
        steps:
            - uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 8.0.x

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore

            - name: Test
              run: dotnet test --no-build --verbosity normal
    
    deploy:
        if: github.ref == 'refs/heads/main' # this prevents the "deploy" job from executing during Pull Request checks
        runs-on: Main
        needs: build
        
        steps:
            - name: Publish
              run: dotnet publish -c Release -o /home/github/LSPDFRHelperMain

            - name: Store build info in file
              run: |
                  BRANCH_NAME=${GITHUB_REF#refs/heads/}
                  echo "Current Branch: $BRANCH_NAME | Commit Hash: $GITHUB_SHA" > /home/github/LSPDFRHelperMain/build_info.txt
              continue-on-error: true

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image
              run: docker build -t superpyromaniac/lspdfrhelpermain:latest /home/github/LSPDFRHelperMain

            - name: Push Docker image to Docker Hub
              run: docker push superpyromaniac/lspdfrhelpermain:latest

            - name: Deploy app
              run: |
                  # Pull the latest image
                  docker pull superpyromaniac/lspdfrhelpermain:latest
                  
                  # Stop and remove the old container
                  docker stop helpermain || true
                  docker rm helpermain || true
                  
                  # Run the new container
                  docker run -d --name helpermain superpyromaniac/lspdfrhelpermain:latest
                  
                  # Optionally, clean up old images
                  docker image prune -f
