# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  deploy:
    if: github.ref == 'refs/heads/main' # this prevents that the "deploy" job is executed during Pull Request checks
    runs-on: self-hosted
    needs: build

    strategy:
      matrix:
        dotnet: ["7.0.x"]
    
    steps:
    - name: Publish
      run: dotnet publish -c Release -o /home/ULSS # replace "/opt/ULSS_Helper" with the actual path to the bot's working directory.

    - name: Restart app
      run: pm2 restart 1 # replace "ULSS_Helper" with the actual pm2 process name.
